baseURL = 'https://disorientcountry.club/'
languageCode = 'en-us'
title = 'Disorient presents: COUNTRY CLUB XIV - PRESENCE AND THE ETERNAL NOW'
theme = 'countryclub'

[build]
  writeStats = true

[caches.assets]
  maxAge = -1

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'hugo_stats.json'
    target = 'assets/watching/hugo_stats.json'

[params]
  description = 'Join Disorient for year 14 of our annual journey of deep chilling, off-the-grid futurist relaxation. Country Club is a lake and lush green woodland oasis where blissful self-reliance meets massive multiplayer techno and technology participation.'

[[menus.main]]
  name = 'Home'
  url = '/'
  weight = 0

[[menus.main]]
  name = 'Announcements'
  url = '/announcements/'
  weight = 1

[[menus.main]]
  name = 'Lineup'
  url = '/lineup/'
  weight = 2

[[menus.main]]
  name = 'Art'
  url = '/art/'
  weight = 3

[[menus.main]]
  name = 'Camps'
  url = '/camps/'
  weight = 4

[[menus.main]]
  name = 'Guide'
  url = '/guide/'
  weight = 5

[[menus.main]]
  name = 'Get Involved'
  url = '/get-involved/'
  weight = 5
